/* DB 계층 카테고리 설계 예시
 * 
 * Oracle 예시
 * 
 * 출처: https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=l1523&logNo=221896455807
 * 
 * 
 */
CREATE TABLE CTG 
(
 	 CTG_NO	 VARCHAR2(8)  NOT NULL PRIMARY KEY,
 	 CTG_NM	 VARCHAR2(100)  NOT NULL,
 	 UP_CTG_NO	 VARCHAR2(8)  NOT NULL,
 	 DISP_YN	 VARCHAR2(1)  NOT NULL,
 	 SEQ	 NUMBER(3),
 	 NOTE	 VARCHAR2(200)   
);

/* 1depth */
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1000', '디지털/가전/컴퓨터', 'M', 'Y', 1);

/* 2depth */
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1001', '카테고리', '1000', 'Y', 1);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1002', '테마 편집샵', '1000', 'Y', 2);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1003', '전문관/브랜드', '1000', 'Y', 3);

/* 3depth */
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1004', 'TV', '1001', 'Y', 1);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1005', '계절가전', '1001', 'Y', 2);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1006', '노트북', '1001', 'Y', 3);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1007', '스마트기기', '1001', 'Y', 4);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1008', '냉장고', '1001', 'Y', 5);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1009', '카메라/주변기기', '1001', 'Y', 6);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1010', '스마트IT', '1002', 'Y', 1);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1011', '본사직영 렌탈샵', '1003', 'Y', 1);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1012', '휴대폰샵', '1003', 'Y', 2);

/* 4depth */
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1013', 'DSLR카메라', '1009', 'Y', 1);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1014', '미러리스카메라', '1009', 'Y', 2);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1015', '일반 디지털카메라', '1009', 'Y', 3);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1016', '필름카메라', '1009', 'Y', 4);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1017', '즉석카메라', '1009', 'Y', 5);
INSERT INTO CTG(CTG_NO, CTG_NM, UP_CTG_NO, DISP_YN, SEQ)
VALUES('1018', '카메라렌즈', '1009', 'Y', 6);

COMMIT;

SELECT * FROM CTG;


SELECT
        LEVEL               LV
      , CONNECT_BY_ISLEAF   LF
      , LPAD('  ', 4 * (LEVEL - 1)) || CTG_NO 카테고리번호
      , LPAD('  ', 4 * (LEVEL - 1)) || CTG_NM 카테고리명
      , SUBSTR(SYS_CONNECT_BY_PATH(CTG_NM, '>'), 2) CTG_PATH
      , CONNECT_BY_ROOT(CTG_NO) CTG_ROOT
FROM    CTG
WHERE   1 = 1
START WITH UP_CTG_NO = 'M'
CONNECT BY PRIOR CTG_NO = UP_CTG_NO
ORDER SIBLINGS BY SEQ, CTG_NO
;


SELECT
        LEVEL               LV
      , CONNECT_BY_ISLEAF   LF
      , LPAD('  ', 4 * (LEVEL - 1)) || CTG_NO 카테고리번호
      , LPAD('  ', 4 * (LEVEL - 1)) || CTG_NM 카테고리명
      , SUBSTR(SYS_CONNECT_BY_PATH(CTG_NM, '>'), 2) CTG_PATH
      , CONNECT_BY_ROOT(CTG_NO) CTG_ROOT
FROM    CTG
WHERE   1 = 1
START WITH CTG_NM = '필름카메라'
CONNECT BY CTG_NO = PRIOR UP_CTG_NO
ORDER SIBLINGS BY SEQ, CTG_NO
;